from __future__ import annotations

import csv
import json
import os
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from modules.common import DATA_DIR
from modules.sqlite_store import SqliteStore
from scripts.generate_henan_field_crop_seed_csv import OUTPUT_DIR


def _load_csv(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def _empty_to_none(value: Any) -> Any:
    return None if value in ("", None) else value


def import_henan_field_crop_seed_csv(seed_dir: Path, db_path: Path) -> dict[str, int]:
    store = SqliteStore(db_path)
    try:
        store.upsert_data_source(
            {
                "source_id": "henan_field_crop_generated_seed",
                "source_name": "河南地块与作物基础 seed",
                "publisher": "muye",
                "region_scope": "河南省",
                "source_type": "generated_seed",
                "source_url": "local://data/seeds/henan/field_crop_seed",
                "access_level": "local",
                "retrieval_date": "2026-04-15",
                "license": "",
                "notes": "Generated by scripts/generate_henan_field_crop_seed_csv.py",
            }
        )

        crop_rows = _load_csv(seed_dir / "crop_catalog.csv")
        field_rows = _load_csv(seed_dir / "fields.csv")
        cycle_rows = _load_csv(seed_dir / "field_crop_cycles.csv")

        for row in crop_rows:
            store.upsert_crop_catalog_record(
                {
                    **row,
                    "growth_cycle_days": _empty_to_none(row.get("growth_cycle_days")),
                    "water_demand_coefficient": _empty_to_none(row.get("water_demand_coefficient")),
                }
            )

        for row in field_rows:
            geofence = _empty_to_none(row.get("geofence"))
            store.upsert_field(
                {
                    **row,
                    "geofence": json.loads(geofence) if geofence else None,
                    "latitude": _empty_to_none(row.get("latitude")),
                    "longitude": _empty_to_none(row.get("longitude")),
                    "area_mu": _empty_to_none(row.get("area_mu")),
                    "area_hectare": _empty_to_none(row.get("area_hectare")),
                }
            )

        for row in cycle_rows:
            store.upsert_field_crop_cycle(
                {
                    **row,
                    "year": _empty_to_none(row.get("year")),
                    "area_mu": _empty_to_none(row.get("area_mu")),
                    "expected_yield_kg": _empty_to_none(row.get("expected_yield_kg")),
                    "actual_yield_kg": _empty_to_none(row.get("actual_yield_kg")),
                }
            )

        return {
            "crop_catalog": len(crop_rows),
            "fields": len(field_rows),
            "field_crop_cycles": len(cycle_rows),
        }
    finally:
        store.close()


def main() -> None:
    seed_dir = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else OUTPUT_DIR
    db_path = Path(os.getenv("MUYE_SQLITE_PATH", str(DATA_DIR / "muye.db")))
    summary = import_henan_field_crop_seed_csv(seed_dir, db_path)
    print(f"Imported {summary['crop_catalog']} crop_catalog rows into {db_path}")
    print(f"Imported {summary['fields']} fields rows into {db_path}")
    print(f"Imported {summary['field_crop_cycles']} field_crop_cycles rows into {db_path}")


if __name__ == "__main__":
    main()
